# Generated by Django 5.2.4 on 2025-07-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_id",
        ),
    ]
