# Generated by Django 5.2.4 on 2025-07-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_products_options_inventory_product_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="product_category",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="product_image",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="product_name",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="product_price",
        ),
    ]
