# Generated by Django 5.2.4 on 2025-08-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='reserved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
