# Generated by Django 5.2.4 on 2025-08-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_products_reserved_alter_products_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
